src/objects/Timecard__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Timecards</relationshipLabel>
        <relationshipName>Timecards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TC-{000000}</displayFormat>
        <label>Timecard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
/****************************************************************************************************************************************** 
* Class Name   : TestDataFactory
* Description  : test data factory class for creating data for testing  method. 
* Created By   : Stack Nexus
*****************************************************************************************************************************************/
@isTest(SeeAllData=true)
public class TestDataFactory {
    
    /*
    * Method name : createUser.
    * Description :  This methods is used to create user.
    * Returns :  User
    */
    public static user createUser() {
        // Setup test data
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        system.debug('profile'+p);
        User usr = new User(Alias = 'tuser', Email='usertest@testorg.com',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='test_user@test123.com');
        system.debug('username'+usr.username);
        insert usr;
        return usr;
    }
    
     /*
    * Method name : insertTimeCard.
    * Description :  This methods is used to insert Timecard.
    * Returns :  User
    */
    public static Timecard__c insertTimeCard() {
        // Setup test data
        Case caseRec = new Case(Subject ='Test Case');
        insert caseRec;
        Timecard__c timeCard = new Timecard__c(RecordTypeId = '0122F0000008vEzQAI', Case__c = caseRec.Id, Hours__c = 10); 
        insert timeCard;
        return timeCard;
    }

}